"""models updated - purchases

Revision ID: 2e13394026ad
Revises: 010486462218
Create Date: 2026-03-06 11:29:05.921206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2e13394026ad'
down_revision: Union[str, Sequence[str], None] = '010486462218'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('business', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.add_column('inventory_movements', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inventory_movements', 'users', ['created_by'], ['id'])
    op.alter_column('orders', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('products', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.create_foreign_key(None, 'purchase_items', 'purchases', ['purchase_id'], ['id'])
    op.create_foreign_key(None, 'purchase_items', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'purchases', 'suppliers', ['supplier_id'], ['id'])
    op.alter_column('sales', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.create_foreign_key(None, 'suppliers', 'business', ['business_id'], ['id'])
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.alter_column('sales', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.drop_constraint(None, 'purchase_items', type_='foreignkey')
    op.drop_constraint(None, 'purchase_items', type_='foreignkey')
    op.alter_column('products', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('orders', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.drop_constraint(None, 'inventory_movements', type_='foreignkey')
    op.drop_column('inventory_movements', 'created_by')
    op.alter_column('business', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    # ### end Alembic commands ###
